services:
  db-service:
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hok-db
    container_name: hok-db
    volumes:
      - /Users/alan/Desktop/docker-data/hok-pick-assistant-postgres-db:/var/lib/postgresql/data
  qdrant-service:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - /Users/alan/Desktop/docker-data/hok-pick-assistant-qdrant-db-qdrant- :/qdrant/storage